version: '3.8'

services:
  # nginx:
  #   container_name: yii-crud-template-nginx
  #   image: nginx:alpine
  #   restart: unless-stopped
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./docker-config/nginx:/etc/nginx/conf.d
  #     - ./app:/var/www/html
  #   depends_on:
  #     - php
  #   networks:
  #     - yii-crud-template

  php:
    container_name: yii-crud-template-app
    build:
      context: .
      dockerfile: Dockerfile
    image: javi98/yii-crud-template:1.1.0
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    networks:
      - yii-crud-template

  mysql:
    container_name: yii-crud-template-db
    image: mariadb:11.2.2
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - yii-crud-template

volumes:
  db-data:

networks:
  yii-crud-template:
    driver: bridge
